G15Purple: images.h File Reference
images.h File Reference
Defines
#define scroll_width 80
#define scroll_height 6
#define proto_width 10
#define proto_height 7
#define g15_res_width 160
#define g15_res_height 43
Functions
void g15rx_drawXBM (g15canvas *canvas, unsigned char *data, int width, int height, int pos_x, int pos_y)
Detailed Description
Author:
Kabili < kabili207@gmail.com
Version:
0.4
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details at http://www.gnu.org/copyleft/gpl.html
A list of XBM images used by G15Purple. All images were created in GIMP. The resulting code was then copied from the .xbm files here. The files may be edited in the same manner.
Definition in file images.h.
Define Documentation
#define g15_res_height 43
Definition at line 175 of file images.h.
Referenced by draw_goodbyeScreen(), and draw_welcomeScreen().
#define g15_res_width 160
Definition at line 174 of file images.h.
Referenced by draw_goodbyeScreen(), and draw_welcomeScreen().
#define proto_height 7
Definition at line 89 of file images.h.
Referenced by draw_messageWindow().
#define proto_width 10
Definition at line 88 of file images.h.
Referenced by draw_messageWindow().
#define scroll_height 6
Definition at line 76 of file images.h.
#define scroll_width 80
Definition at line 75 of file images.h.
Function Documentation
void g15rx_drawXBM (g15canvas * canvas, unsigned char * data, int width, int height, int pos_x, int pos_y)
Renders XBM image files to the screen.
Author:
Rynor < http://www.g15tools.com/forum/viewtopic.php?p=333#p333
Parameters:
canvas Canvas which will be written to
data The XBM file data that is to be displayed. Stored in a char array.
width The width of the image
height The height of the image
pos_x The X coordinate the top left of the image is to be drawn
pos_y The Y coordinate the top left of the image is to be drawn
Definition at line 43 of file images.h.
Referenced by draw_goodbyeScreen(), draw_messageWindow(), and draw_welcomeScreen().